project:
  type: sdca-theme

website:
  title: "ResearchOps"
  site-url: "https://steno-aarhus.github.io/research-ops/"
  repo-url: "https://github.com/steno-aarhus/research-ops"
  navbar:
    pinned: true
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/"
      - icon: twitter
        href: "https://twitter.com/StenoAarhusRes"
      - icon: globe
        href: directory.qmd

format: sdca-theme-html

editor:
  markdown:
    wrap: 72
    canonical: true

