---
title: "Research Operations"
subtitle: "Refining, simplifying, and streamlining the entire research lifecycle."
---

::: callout-warning
This is very much a work-in-progress!
:::

Research Operations (ResearchOps) is about designing and building (or
improving) the social, organizational, and technical infrastructures
that underlie the research lifecycle to be simpler, easier, and faster.

The main aim is to reduce non-creative or non-social work at SDCA by
automating or streamlining them, as well as to provide training,
documentation, and templates to simplify work that can't be automated or
streamlined.

How will this help out at SDCA? By making the research lifecycle the
focus for our work, we can do research (and other tasks) at Steno
faster, better, and easier.

```{mermaid}
%%| echo: false
%%| fig-cap: "An evolving diagram of (some) components within ResearchOps. The bolded items are projects related to their connected components that we are working on. Clicking on any of them will send you to their website that has more information about them."
flowchart LR
  main(("ResearchOps")) --> guides("Guidelines\nand templates")
  main --> tools("Tools")
  main --> data-ops("Data Operations")
  main --> social-relations("Social\nrelations")
  main --> proj-management("Project\nmanagement")
  main --> capabilities("Capabilities and\nopportunities")
  main --> organizational("Organizational\nmanagement")

  tools --> seedcase["Seedcase"]:::wip
  guides --> common-docs["Common Docs"]:::wip
  data-ops --> seedcase
  capabilities --> r-courses["Reproducible Research\nin R courses"]:::wip

  %% To add later?
  %% main --> knowledge-management("Knowledge\nmanagement")
  %% software("Software") --> automation["Automation"]
  %% data-ops --> data-management["Data management"]
  %% logistics --> participant-recruitment["Participant\nrecruitment"]

  classDef wip stroke:#000,stroke-width:1.2px
  click seedcase "https://seedcase-project.org/" "Seedcase Project"
  click common-docs "https://steno-aarhus.github.io/research/" "Steno Common Docs"
  click r-courses "https://r-cubed.rostools.org/" "r-cubed courses"
```

## Our current focuses

-   Collaborate with researchers and staff to identify tasks that are
    repetitive and/or done regularly, and try to convert them to easier
    and faster
-   Work with researchers to help convert intensive, time-consuming
    analyses to be faster
-   Develop and run training sessions or tutorials on different aspects
    within ResearchOps

## Send us ideas for work!

If you have any tasks or activities that you do fairly often, that is
repetitive, that doesn't require much creative work, or that is a
complex analytical (not statistical) coding problem, maybe we can work
together to help out! Let us know by filling in the form below and we
can set up a time to chat about it!

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSe19WX7ZkB_EUzmDH89lFDRnfblP9-6lo3fxXU_eWiHFO6cOg/viewform?embedded=true" width="650" height="750" frameborder="0" marginheight="0" marginwidth="0">

Loading...

</iframe>
